### ISSUE TITLE
Отображать выставленные пользователем ордера в стакане

### ISSUE THREAD

**Issue by 0n0t0le** [blckchnd/rudex-ui#11]
+ выделять жирным ордера с объемом выше определенного (т.н. стенки)

ПРИМЕР:

![](https://s29.postimg.org/sc9e31mo7/image.png)

**Comment by DimaBLCKCHND** [comment]
Вот этого очень не хватает 

Если не цветом, то звездочкой

**Comment by xanoxt** [comment]
Запостил в апстрим https://github.com/bitshares/bitshares-ui/issues/302

**Comment by xanoxt** [comment]
Поправьте тэг, я это делать не могу.

**Comment by ruslansalikhov** [comment]
перемещено в апстрим
