### ISSUE TITLE
Закрыть вопрос с использованием Троллбокса [БЕЗОПАСНОСТЬ]

### ISSUE THREAD

**Issue by 0n0t0le** [blckchnd/rudex-ui#12]
Рассмотреть ~~возможность запуска Чатбро на своем сервере~~ / альтернативные решения (для TG-based)

**Comment by ruslansalikhov** [comment]
Если будут находиться какие нибудь решения, скидывайте сюда пожалуйста. Пока не нашел чего либо стоящего. И ничего с поддержкой тг.

**Comment by 0n0t0le** [comment]
Закрыто, пересоздал #67

**Comment by 0n0t0le** [comment]
Закрыто, пересоздали #67
