### ISSUE TITLE
Исправить алгоритм ввода суммы сделки и\или цены.

### ISSUE THREAD

**Issue by Smailer-x** [blckchnd/rudex-ui#15]
При клике в поля для создания ордера, значения "0" автоматически не заменяется на вводимую сумму, а дописываются спереди или позади "0" и приходится редактировать вручную
См анимацию:

![zero_problem](https://cloud.githubusercontent.com/assets/22348661/24841826/c9cd2d7c-1d95-11e7-824c-0670fdc93de0.gif)

**Comment by 0n0t0le** [comment]
Проверить на других клиентах (OL...)

**Comment by Smailer-x** [comment]
Проверил, на OL, все четко.
В десктоп и WEB клиенте битшар - проблема с нулем.

![bs](https://cloud.githubusercontent.com/assets/22348661/25040093/0cd398d6-2110-11e7-95d8-47d9c07855ea.gif)


если быть наблюдательным, то OL использует разрядность `0.0` вместо `0`

![ol](https://cloud.githubusercontent.com/assets/22348661/25039952/2fced284-210f-11e7-929a-b2f22dbd6e75.gif)
