### ISSUE TITLE
Не отображается выбор избранной пары (звездочка)

### ISSUE THREAD

**Issue by 0n0t0le** [blckchnd/rudex-ui#18]
Очевидно - сломалось после фикса иконки Приватных ключей

![](https://s14.postimg.org/7134rchgx/image.png)

**Comment by ruslansalikhov** [comment]
Fixed. Можно посмотреть фикс на https://testnet.rudex.org

**Comment by 0n0t0le** [comment]
Подтверждаю, все ок
