### ISSUE TITLE
Дашборд -Последния действия - исполненные ордера - отображаются не все

### ISSUE THREAD

**Issue by 0n0t0le** [blckchnd/rudex-ui#20]
Собственно где все остальное:?
отображает только последние сутки?

![](https://s9.postimg.org/i3pqt6zcv/image.png)

**Проверить!**

**Comment by Smailer-x** [comment]
проверил  в Chrome

![image](https://cloud.githubusercontent.com/assets/22348661/24916730/a2f93408-1ee3-11e7-8977-cc5796c59d6e.png)

**Comment by 0n0t0le** [comment]
Я тебя вижу вот так:

![](https://s29.postimg.org/5489fie4n/image.png)

Надо ковырять

**Comment by lososeg** [comment]
Тоже самое в десктопной версии. На данный момент могу видеть только за последние 17 дней. Хотя первый ввод был месяц назад. Через экспорт в csv тоже вижу только последние 17 дней.
