### ISSUE TITLE
 Регистрация прошла через кран OL !!!

### ISSUE THREAD

**Issue by 0n0t0le** [blckchnd/rudex-ui#23]
15 минут назад был зареган аккаунт (по модели аккаунта) через rudex.org

Регистратором выступил **openledger**

![](https://s7.postimg.org/zbkgknpjv/image.jpg)

На всякий случай, была выбрана по дефолту API нода OL, но это не должно влиять

![](https://s28.postimg.org/avo7s7xnh/image.jpg)

**Comment by on0support** [comment]
Все тоже самое, проверил. Интересно, когда появилось.
![image](https://cloud.githubusercontent.com/assets/27305250/24955178/0c4b61ae-1f8b-11e7-8624-0683cb467af4.png)

**Comment by ruslansalikhov** [comment]
Исправлено в свежей версии.. Обновляйте кэш или ждите пару часов.
