### ISSUE TITLE
Чтобы не плодить сущности - предлагаю все проблемы с локализацией оставлять ниже

### ISSUE THREAD

**Issue by on0support** [blckchnd/rudex-ui#27]
Публикуем со скринами в комментарии

**Comment by on0support** [comment]
![image](https://cloud.githubusercontent.com/assets/27305250/25084141/a7ac78dc-2363-11e7-86d3-a0c773057149.png)
всплывающее окно обрезается

**Comment by on0support** [comment]
![image](https://cloud.githubusercontent.com/assets/27305250/25084169/c50a6574-2363-11e7-9f97-f4949a95301e.png)
synchronized - синхронизирован

**Comment by on0support** [comment]
![image](https://cloud.githubusercontent.com/assets/27305250/25084174/cf34134c-2363-11e7-8269-94276e85cbf4.png)
filter - фильтровать

**Comment by on0support** [comment]
![image](https://cloud.githubusercontent.com/assets/27305250/25084189/d7b6233e-2363-11e7-9eed-d9ed3af7b5a2.png)
copy adress - скопировать адрес

**Comment by on0support** [comment]
![image](https://cloud.githubusercontent.com/assets/27305250/25084196/df6045ba-2363-11e7-87a6-76bc93308783.png)
fiat - фиат
Сlick here to …  deposit - Нажмите здесь для регистрации, чтобы внести средства

 Сlick here to …  withdraw - Нажмите здесь для регистрации, чтобы вывести средства

**Comment by on0support** [comment]
![image](https://cloud.githubusercontent.com/assets/27305250/25084200/ea62048a-2363-11e7-844f-e5f88cd88f0c.png)
Кривая надпись «ОТПРАВЬТЕ ВАШИ НА АДРЕС НИЖЕ» 

transaction history -  история транзакций 

show transaction history -  показать историю транзакций

**Comment by on0support** [comment]
![image](https://cloud.githubusercontent.com/assets/27305250/25084201/f38c5ce0-2363-11e7-91b5-fae1b444a93a.png)
refresh -обновить 
No withdrawals  - нет снятий 
No deposit  - нет депозитов

**Comment by on0support** [comment]
![image](https://cloud.githubusercontent.com/assets/27305250/25084203/faa3b460-2363-11e7-9e70-4e1a8e81d0a1.png)
your account -ваш аккаунт

**Comment by on0support** [comment]
![image](https://cloud.githubusercontent.com/assets/27305250/25084212/07d2f484-2364-11e7-91be-5d06adfdcb04.png)
надо подправить перевод

**Comment by 0n0t0le** [comment]
![image](https://cloud.githubusercontent.com/assets/22417528/25871710/1d7274e0-3511-11e7-8bc8-aa9c026df105.png)

**Comment by 0n0t0le** [comment]
При восстановлении кошелька, если ранее была попытка создать модель аккаунта
![image](https://cloud.githubusercontent.com/assets/22417528/26171833/0882ec42-3b4f-11e7-8444-2d60749ebb2c.png)

**Comment by 0n0t0le** [comment]
![default](https://cloud.githubusercontent.com/assets/22417528/26206194/cdab26b8-3bec-11e7-9ef3-b19f32fc030b.png)

**Comment by 0n0t0le** [comment]
![image](https://cloud.githubusercontent.com/assets/22417528/26219884/503b2e80-3c19-11e7-8c81-30da9b3f9e3d.png)

**Comment by ghost** [comment]
![Image](http://i.imgur.com/MNOAbOm.png)
Два раза "на" в тексте

**Comment by ruslansalikhov** [comment]
@sanchomalyutin исправлено. В ближайшее время попадет в релиз.
