### ISSUE TITLE
Не отображаются ассеты, эмитированные пользователем

### ISSUE THREAD

**Issue by 0n0t0le** [blckchnd/rudex-ui#28]
В нашем клиенте не отображаются ассеты, эмитированные пользователем, в частности наш BitRUBLE
https://market.rudex.org/account/blckchnd/assets/

В родном клиенте шар все ок:
https://bitshares.org/wallet/#/account/blckchnd/assets/
![](https://s12.postimg.org/rkhw6140d/image.png)

**Comment by DimaBLCKCHND** [comment]
в десктопе также не отображаются
