### ISSUE TITLE
В депозитах через шлюз OL отсутствует OPEN.LISK

### ISSUE THREAD

**Issue by 0n0t0le** [blckchnd/rudex-ui#29]
В свою очередь на Openledger возможность ввода/вывода имеется. Данная проблема на битшарес орг и у нас соответственно. 
P.S.
Предлагаю поставить их в известность - пусть чинят

**Comment by DimaBLCKCHND** [comment]
Написал Ронни в общем чате

**Comment by 0n0t0le** [comment]
Это не Ронни надо писать, косяк в bitshares.org клиенте
