### ISSUE TITLE
Проверить работу реф. системы при регистрации по нашей ссылке

### ISSUE THREAD

**Issue by 0n0t0le** [blckchnd/rudex-ui#39]
![default](https://cloud.githubusercontent.com/assets/22417528/25629812/9264587a-2f73-11e7-9360-650089383030.png)

![default](https://cloud.githubusercontent.com/assets/22417528/25629822/9a69fa7a-2f73-11e7-9a4d-29b1d3e56b5b.png)

![default](https://cloud.githubusercontent.com/assets/22417528/25629831/a40954cc-2f73-11e7-9646-289f24641360.png)

![default](https://cloud.githubusercontent.com/assets/22417528/25629839/a831d34e-2f73-11e7-8200-7cfce04be280.png)

**Comment by ruslansalikhov** [comment]
Это список тех, для кого мы были рефералом. Но регистрировал их другой регистратор.

**Comment by 0n0t0le** [comment]
Либо можно зарегатся и через нас, но используя прямую реф ссылку
