### ISSUE TITLE
В разделе "Мои сделки" отображаются не все исполненные ордера

### ISSUE THREAD

**Issue by 0n0t0le** [blckchnd/rudex-ui#4]
![](https://s18.postimg.org/449dgnjuh/image.png)

**Comment by 0n0t0le** [comment]
Проверить с разных аккаунтов/клиентов/браузеров/устройств

**Comment by 0n0t0le** [comment]
Тут вообще истории нет, хотя закуплено 500+ CNY (возможно отображает только за **посл сутки???**)
![](https://s28.postimg.org/x99sdh425/image.jpg)

**Comment by ruslansalikhov** [comment]
нужно это перенести в апстрим. Подтягивание большей истории.

**Comment by antonblockchain** [comment]
Желательно видеть свою историю сделок.

**Comment by xanoxt** [comment]
Когда нужно что-то перенести в апстрим тегайте/асигните пожалуйста меня. Спасибо. :-)
