### ISSUE TITLE
Добавить следующие ASSETS в основные торгуемые пары

### ISSUE THREAD

**Issue by 0n0t0le** [blckchnd/rudex-ui#41]
**Приоритетно**
OBITS
ICOO
BLOCKPAY
BTSR
***
**Приоритетно**
OPEN.DGD
OPEN.DOGE
OPEN.LTC
OPEN.GRC
***
_**(не приоритетно, но желательно)**_
OPEN.MAID
OPEN.LISK
OPEN.WAVES
OPEN.ARDR
*Этих почему то нет в шлюзе ОЛ*

**Comment by 0n0t0le** [comment]
Если что забыл, добавляйте

**Comment by 0n0t0le** [comment]
В дополнение к этому 
https://github.com/blckchnd/rudex-ui/issues/29

**Comment by 0n0t0le** [comment]
Проверить все OPEN ассеты на возможность ввода/вывода

**Comment by ruslansalikhov** [comment]
Добавил в тестнет
