### ISSUE TITLE
Добавить уведомление об ошибочно введенном пароле 

### ISSUE THREAD

**Issue by 0n0t0le** [blckchnd/rudex-ui#44]
При попытке залогиниться через модель аккаунта

***

кстати как насчет сделать лимит на количество неправильных логинов с одного адреса?

**Comment by ruslansalikhov** [comment]
У нас не клиент серверная архитектура.

Это или делать в апи сервере по серии подозрительных запросов (блокировать доступ к апи серверу с этого адреса). Или просто в нашей морде исскуствено блокировать морду (человек конечно может расковырять этот блок - так что второе это больше зашита от школьников.

Нужно рассмотреть, может можно средствами IT решений блокировать API сервер. НО пользователь сможет выбрать другой.

**Comment by 0n0t0le** [comment]
А регистрации с одного айпи чаще 300 сек. сейчас блокируются каким образом?

**Comment by ruslansalikhov** [comment]
Это блокируется фауцетом-сервером. Он просто не принимает запрос на оплату регистрации с одного и того же ip чаще 300 сек. Как описал выше - мы поставленную задачу можем делать тоже только на своей апи ноде. Остальное не под нашим контролем.

**Comment by 0n0t0le** [comment]
Ну вторую часть пока оставим. По первой части на самом деле уведомление о неверном пароле приходит, проблема в том, что при повторном неверном вводе не происходит никакого обновления страницы, поэтому юзеру вообще не понятно, не валиден ли новый проль, или это старое сообщение.
