### ISSUE TITLE
Не активна кнопка Вывод (при использовании шлюза OL) - MacOS

### ISSUE THREAD

**Issue by 0n0t0le** [blckchnd/rudex-ui#55]
Хром / сафари / десктоп
![default](https://cloud.githubusercontent.com/assets/22417528/26389944/059f32fe-4065-11e7-870b-b25e38d302a5.png)
```
app.js:29 Uncaught (in promise) Error: Missing private memo key for sender: 1.2.177038
    at app.js:29
    at <anonymous>
```

**Comment by ruslansalikhov** [comment]
У пользователя нет приватного ключа от текущего memo ключа.
Нужно или его (приватный) импортнуть, или поменять текущий memo - на текущий active ключ.

**Comment by 0n0t0le** [comment]
закрываю
