### ISSUE TITLE
В разделе мои рынки цена значительно отличается от последней рыночной цены

### ISSUE THREAD

**Issue by 0n0t0le** [blckchnd/rudex-ui#64]
См. Blockpay , рыночная цена на момент написания 1,25

![default](https://user-images.githubusercontent.com/22417528/27226333-2fcb0720-52a7-11e7-89ae-585801bc2a1a.png)

**Comment by lososeg** [comment]
такое происходит при отсутствии сделок больше 24 часов
![default](https://user-images.githubusercontent.com/29502537/27264736-d722121a-548d-11e7-88ec-b3e873ef4a1a.png)
