### ISSUE TITLE
Не отображается (свеже)выставленный ордер в моих ордерах

### ISSUE THREAD

**Issue by 0n0t0le** [blckchnd/rudex-ui#65]
Из особенностей - курс в 100 раз выше текущего()
![](https://s9.postimg.org/nbv39hhof/image.png)

**Comment by lososeg** [comment]
Новую ветку плодить не буду.
Не отображаются и старые ордера на этой вкладке. На вкладке Аккаунт при нажатии на "Отобразить открытые ордера" все нормально.
![1](https://user-images.githubusercontent.com/29502537/27768762-e575f0ac-5f23-11e7-8248-c4ed7a96c420.png)
![2](https://user-images.githubusercontent.com/29502537/27768763-e57852ac-5f23-11e7-89b7-f19391f18b50.png)

З.Ы. десктоп приложение, винда 10
