### ISSUE TITLE
Trollbox in iframe

### ISSUE THREAD

**Issue by ruslansalikhov** [blckchnd/rudex-ui#67]
1) Необходимо перенести плавающий чат ChatBro: http://prntscr.com/g5e0ly

на страницу Биржи в фрейм: http://prntscr.com/g5e1ct, адрес чата https://rudex.chatbro.com/
закрепив его на панели справа.

2) Секция с чатом должна быть сворачиваемой, так же как и график

3) Секция с чатом должна быть изменяемой в высоту

4)* Должны работать переходы по ссылкам (ссылки открываются в новом окне)

5)* frame должен работать в режиме песочницы. Чтобы из него нельзя было собирать какую либо информацию о действиях пользователя и как то влиять на хост-страницу.

(*) - если это возможно.

**Comment by 0n0t0le** [comment]
График (глубину рынка) если не ошибаюсь, мы решили убрать в итоге. А Троллбокс по итогу прибить в определенной области окна (хотя он все равно будет сворачиваемым и с динамической высотой/шириной)
