### ISSUE TITLE
Добавление возможности закладывать MPA из UI

### ISSUE THREAD

**Issue by LastWarrior** [blckchnd/rudex-ui#74]
## Проблема
Сейчас в интерфейсе реализована возможность закладывать только core токен (BTS) для выпуска MPA, хотя БЧ позволяет выпускать MPA закладывая другие MPА.
Такой ограничивающий фактор сдерживает возможность эмиссии MPA и отрицательно сказывается на развитии системы, т.к. от оборотов MPA напрямую зависит капитализация BitShares, через пополнение резервного пула при получении комиссии. 
Тем более сейчас у пользователей мало мотивации выпускать MPA, но есть те, у кого выпущен актив, который он не может продать из за низкой ликвидности (bitSilver, bitBTC) по интересующей его цене, но может его заложить, чтобы выпустить другой MPA (например, bitUSD).

Можно запросить расчет актива в базовый актив, но для этого потребуется 24 часа и если у пользователя на руках bitGold, который не может быть продан по интересующей его цене, он мог бы его заложить и выпустить bitUSD, например, для оплаты чего либо, что нужно купить сейчас и нет возможности ждать.

## Решение
Требуется доработать UI:
1. В модальном окне настроек залогового обеспечения, там где указывается сумма залога и закладываемый актив нужно сделать выпадающий список MPA, которые можно заложить.
2. При выборе из списка нужного актива, требуется обновить доступный баланс, который отображается над input полем для ввода суммы залога.

**Comment by cptn-solo** [comment]
@LastWarrior сейчас только подумал, что кейс 

>  но есть те, у кого выпущен актив, который он не может из за низкой ликвидности (bitSilver, bitBTC)

на самом деле не очень актуальный, т.к. любой бит-актив можно вернуть блокчейну (попросить расчет/ settlement) в обмен на базовый актив.

**Comment by LastWarrior** [comment]
Дополнил кейс:

_Можно запросить расчет актива в базовый актив, но для этого потребуется 24 часа и если у пользователя на руках bitGold, который не может быть продан по интересующей его цене, он мог бы его заложить и выпустить bitUSD, например, для оплаты чего либо, что нужно купить сейчас и нет возможности ждать._

**Comment by cptn-solo** [comment]
@UspenskyDritry коллега, надо делать. Нам тоже надо. Реально.

**Comment by antonblockchain** [comment]
Надо. пример сейчас у меня bitUSD и я хочу шорт по bts или bitBTC.
Такое решение даст возможность шортить биткоин относительно фиата

**Comment by akledirs** [comment]
На уровне протокола доступна функция залога в битактивах, но только для смарткоинов, в которых в качестве backed asset установлен данный актив. Это не имеет отношения к интерфейсу
