### ISSUE TITLE
Ошибка в уведомлении о неработающем шлюзе

### ISSUE THREAD

**Issue by ghost** [blckchnd/rudex-ui#75]
Скорее всего сообщения, что не работает шлюз для ОЛ и RuDEX перепутаны, т.е. при неработающем шлюзе ОЛ я видел сообщение, что не работает шлюз RuDEX и наоборот.

**Comment by ruslansalikhov** [comment]
Fixed by https://github.com/blckchnd/rudex-ui/commit/0cace31b66673541eac85218a799f67536aeecd8
