### ISSUE TITLE
В разделы Отправить / Вывести добавить кнопку ВЫВЕСТИ ВСЕ

### ISSUE THREAD

**Issue by 0n0t0le** [blckchnd/rudex-ui#8]
При нажатии должен быть произведен расчет суммы для вывода за вычетом стандартной комиссии, и автоматически подставлен в поле `СУММА`

![](https://s15.postimg.org/5aadqxtsb/image.jpg)

**Comment by xanoxt** [comment]
Похожее ишью: https://github.com/bitshares/bitshares-ui/issues/85
