### ISSUE TITLE
Не отображается открытый ордер в десктопном клиенте для мака

### ISSUE THREAD

**Issue by VELLEVET** [blckchnd/rudex-ui#82]
В веб-версии по этой ссылке ордер отображается (в блоке "Мои открытые ордера"):
https://market.rudex.org/#/market/BTS_USD

В десктопной версии **для мака** - не отображается.
При этом в десктопной версии инфа об ордере есть в разделе "Аккаунт" - во вкладках: "Обзор" и "Открытые ордера".

Скрины:
- https://imgur.com/a/DfhbU (Аккаунт:Открытые_ордера - инфа есть)
- https://imgur.com/a/xbBnb (Аккаунт:Обзор - инфа есть)
- https://imgur.com/a/8k7MN (торговля BTS_USD - **инфы нет**)

**Comment by ruslansalikhov** [comment]
@VELLEVET Добрый день.

А в обновленной десктопной версии так же?

**Comment by VELLEVET** [comment]
@ruslansalikhov 
Только что и первый раз скачал версию RuDEX-2.0.180115.dmg отсюда:
- https://github.com/blckchnd/rudex-ui/releases
