### ISSUE TITLE
White screen after mistake in asset URL

### ISSUE THREAD

**Issue by Kwaskoff** [blckchnd/rudex-ui#95]
Describe the bug
white screen
To Reproduce by 2 browser

For Firefox 64
    Open https://market.rudex.org/#/market/BTK_BTS
Change in URL "BTK" to "BTC"
    See error
For Chromium Version 71.0.3578.98
    Open https://market.rudex.org/#/market/BTK_BTS
Change in URL "BTK" to "BTC"
Change in URL "BTC" to "BTK"
Change in URL "BTK" to "BTC"
    See error

OS: Ubuntu Desktop 18.04 64-bit

![console](https://i.imgur.com/GrfbSR1.png "error")

**Comment by Kwaskoff** [comment]
One year, Carl! One year this bug is!

**Comment by siralexpu** [comment]
> One year, Carl! One year this bug is!

попробуй: https://dev.rudex.org/

будет поддерживаться новая версия вскоре
старая не будет поддерживаться и исправляться
